---
inventory:  
  build: .
  command: npm start
  ports:
  - "8080:8080"
  links:
  - mongodb
  - mongodb:mongodb.cloud66.local
  environment:
    - NODE_ENV=production
    - MONGODB_ADDRESS=35.177.160.3
    - DBUSERNAME=readerWriter
    - DBPASSWORD=password
mongodb:  
  image: mongo
