---
services:

  inventory:
    git_url: https://github.com/jamesHargreaves12/new_grey_db_api.git
    git_branch: master
    command: npm start
    build_root: .
    ports:
      - container: 8080
        http: 80
        https: 443
    env_vars:
      NODE_ENV: production
      MONGODB_ADDRESS: 35.177.160.3


databases:  
  - mongodb
